sequenceDiagram
    autonumber
    广告投放平台->>+用户: 展示广告（曝光）
    用户->>-广告投放平台: 点击广告
    广告投放平台->>+归因监控平台: 上报用户点击
    rect rgb(0, 128, 255, 0.1)
        用户-->>下载渠道: 下载 APP
        下载渠道-->>APP: 安装 APP
        用户-->>APP: 启动 APP
        Note over 用户,APP: 用户自主行为
    end
    APP->>归因监控平台: 上报信息
    归因监控平台->>归因监控平台: 归因分析
    归因监控平台->>-广告投放平台: 回调归因数据