sequenceDiagram
    autonumber
    用户设备->>+用户: 展示广告（曝光）
    用户->>-用户设备: 点击广告
    用户设备 -->> 用户设备: 获取设备广告ID
    Note right of 用户设备: 展示广告时，归因平台的SDK获取到设备的广告ID
    用户设备 ->> 归因平台: 发送广告ID
    归因平台 -->> 归因平台: 记录广告ID
    Note left of 归因平台: 归因平台记录这一次广告点击
    归因平台 ->>+ 下载渠道: 下载
    Note left of 下载渠道: 归因平台跳转到下载渠道
    下载渠道 ->>- 用户设备: 安装APP
    用户设备 ->> 归因平台: 发送广告ID
    Note right of 用户设备: APP内嵌的归因平台SDK上报广告ID
    归因平台 -->> 归因平台: 广告ID匹配，归因成功