(function(){!google.nocsixjs&&google.timers&&google.timers.load.t&&(google.timers.load.t.xjses=(new Date).getTime());})();
(function(){var e={},f=!1,g=function(b,c,a){try{var d=e[c[a][0]];if(d&&d[b])d[b](c[a][1])}catch(m){google.ml(m,!1,{cause:"m"+b,index:a,mid:c[a]&&c[a][0]})}};if(google.mc&&google.j)for(var h=0,i;i=google.mc[h++];)if(i[0]==29){google.j.cfg=i[1];break}var j=null,k,l;function n(){var b=j.value;l=b?eval("("+b+")"):{}}google.med=function(b){if(google.mc){for(var c=google.mc.concat(google.smc||[]),a=0,d=c.length;a<d;a++)g(b,c,b=="dispose"?d-a-1:a);if(b=="dispose")google.mc=null,google.smc=null;f=b!="dispose"}};
google.register=function(b,c){e[b]=c;if(google.smc&&f)for(var a=0,d=google.smc.length;a<d;a++)google.smc[a][0]==b&&g("init",google.smc,a)};google.save=function(b,c){if(j){var a;a:{if(google.mc){a=0;for(var d;d=google.mc[a++];)if(d[0]==b){a-=1;break a}}a=-1}if(a>=0)google.mc[a][1]=c,n(),l[k]=google.mc,j.value=google.stringify(l)}};google.initHistory=function(){k=google.kEI;if(j=document.getElementById("hcache"))if(n(),l[k])google.mc=l[k]};})();
(function(){var h=void 0,i=null;var k=function(a,b,c,d){a=a.split(".");c=c||window;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)if(!a.length&&b!==h){if(!c[e]||!d)c[e]=b}else c=c[e]?c[e]:c[e]={}};google.exportSymbol=function(a,b,c){k(a,b,c)};google.exportDefaultSymbol=function(a,b,c){k(a,b,c,!0)};google.exportProperty=function(a,b,c){a[b]=c};google.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c};var m={a:!1,h:!1,b:!1,opera:!1},n={a:!1,g:!1,m:!1,i:!1,j:!1,k:!1,e:!1,d:!1,c:!1,opera:!1};m.version="";n.version="";
var o=function(a){for(var b in m)m[b]=!1;for(var c in n)n[c]=!1;b=c=i;if(window.opera)m.opera=!0,n.opera=!0,c=b=/Opera\/(\S+)/;else if(a.indexOf("MSIE")>=0)m.a=!0,n.a=!0,c=b=/MSIE\s+([^\);]+)(\)|;)/;else if(a.indexOf("WebKit")>=0){m.b=!0;if(a.indexOf("Chrome")>=0)n.e=!0,b=/Chrome\/(\S+)/;else if(a.indexOf("Android")>=0&&a.indexOf("Mobile")<0)n.d=!0,b=/Version\/(\S+)/;else if(a.indexOf("Android")>=0&&a.indexOf("Mobile")>=0)n.c=!0,b=/Version\/(\S+)/;else if(a.indexOf("Safari")>=0)n.m=!0,b=/Version\/(\S+)/;
if(a.indexOf("iPad")>=0)n.i=!0;else if(a.indexOf("iPhone")>=0)n.j=!0;else if(a.indexOf("iPod")>=0)n.k=!0;c=/WebKit\/(\S+)/}else if(a.indexOf("Gecko")>=0){m.h=!0;if(a.indexOf("Firefox")>=0)n.g=!0,b=/Firefox\/(\S+)/;c=/rv\:([^\);]+)(\)|;)/}if(c)c=c.exec(a),m.version=c?c[1]:"";if(b)c=b.exec(a),n.version=c?c[1]:"";google.browser=google.browser||{};google.browser.engine={IE:m.a,GECKO:m.h,WEBKIT:m.b,OPERA:m.opera,version:m.version};google.browser.product={IE:n.a,FIREFOX:n.g,SAFARI:n.m,IPAD:n.i,IPHONE:n.j,
IPOD:n.k,CHROME:n.e,ANDROID_TABLET:n.d,ANDROID_MOBILE:n.c,OPERA:n.opera,version:n.version}};o(google.ua||window.navigator.userAgent);
var p=function(a,b){function c(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}for(var d=0,e=a.replace(/^\s+|\s+$/g,"").split("."),f=b.replace(/^\s+|\s+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var w=e[j]||"",l=f[j]||"",Q=RegExp("(\\d*)(\\D*)","g"),R=RegExp("(\\d*)(\\D*)","g");do{var q=Q.exec(w)||["","",""],r=R.exec(l)||["","",""];if(q[0].length==0&&r[0].length==0)break;d=c(q[1].length==0?0:parseInt(q[1],10),r[1].length==0?0:parseInt(r[1],10))||c(q[2].length==0,r[2].length==
0)||c(q[2],r[2])}while(d==0)}return d};google.browser=google.browser||{};google.browser.init=o;google.browser.compareVersions=p;google.browser.isEngineVersion=function(a){return p(m.version,a)>=0};google.browser.isProductVersion=function(a){return p(n.version,a)>=0};var s=/^(\w+)?(?:\.(.+))?$/,t=/^#([\w-]+)$/,u=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)},v=function(a,b){var c;if(c=a.match(t)){var d=document.getElementById(c[1]);return d?[d]:[]}c=a.match(s);d=c[2]&&RegExp("\\b"+c[2]+"\\b");c=(b||document).getElementsByTagName(c[1]||"*");for(var e=[],f=0,g;g=c[f++];)(!d||d.test(g.className))&&e.push(g);return e},x=function(a){return a.textContent||a.innerText||""};
google.dom={append:u,create:function(a,b){var c=a.match(s),d=document.createElement(c[1]);if(c[2])d.className=c[2];if(b)d.innerHTML=b;return d},get:function(a,b){return v(a,b)[0]||i},getAll:v,getText:x,insert:function(a,b,c){return b.parentNode.insertBefore(a,c?b.nextSibling:b)},remove:function(a){return a&&a.parentNode&&a.parentNode.removeChild(a)},set:function(a,b){for(var c=1;c<arguments.length;c+=2){var d=arguments[c],e=arguments[c+1],f=a.style;if(f&&d in f)f[d]=e;else if(d in a)a[d]=e;else if(m.a&&
f&&d=="opacity")a.zoom=1,d=(f.filter||"").replace(/alpha\([^)]*\)/,""),isNaN(parseFloat(e))||(d+="alpha(opacity="+e*100+")"),f.filter=d}return a}};google.listen=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};google.unlisten=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c)};var y={},z=function(a,b){return a[1]-b[1]},A=function(a,b,c,d){var e=c===h?!0:c,f=c===!1,g=b&&b[0]===c;if(a in y){d===h&&(d=!1);var j;j=typeof d=="function"?d:function(a){return a===d};for(var w=0,l;l=y[a][w++];)if(l=l[0].apply(i,b||[]),f)e=e||l;else if(g&&(b[0]=l),e=l,j(e))return e}return typeof d=="function"?c:e};
google.msg={listen:function(a){var b=0,c=arguments,d=c.length;d%2==1&&(b=c[d-1]);for(var e=0;e<d-1;e+=2){var f=c[e];y[f]||(y[f]=[]);y[f].push([c[e+1],b]);y[f].sort(z)}},unlisten:function(a){for(var b=0;b<arguments.length-1;b+=2){var c=y[arguments[b]];if(c)for(var d=arguments[b+1],e=0;e<c.length;++e)if(c[e][0]==d){c.splice(e,1);break}}},send:A};var B,C=window.location.protocol+"//"+window.location.host,D=function(a,b,c){if(!A(32,[a,b,c],!1))try{if(RegExp("^("+C+")?/(url|aclk)\\?.*&rct=j(&|$)").test(a))if(b)google.r=1,b.location.replace(a);else{if(!B)B=document.createElement("iframe"),B.style.display="none",u(B);google.r=1;B.src=a}else window.location.href=a}catch(d){window.location.href=a}},E=function(){var a=window.location,b=a.hash?a.href.substr(a.href.indexOf("#")+1):"",c=b&&b.match(/(^|&)q=/),d=a.search?a.href.substr(a.href.indexOf("?")+
1).replace(/#.*/,""):"",b=(c?b:d).replace(/(^|&)(fp|tch)=[^&]*/g,"").replace(/^&/,"");return(c?"/search":a.pathname)+(b?"?"+b:"")},F=function(){var a=window.location;return a.hash?a.href.substr(a.href.indexOf("#")):""},G=function(a,b){var c,d=b?(c=b.indexOf("#"))>=0&&b.substr(c):F();return(c=d&&d.match("[#&]"+(b?"(q|fp)":"fp")+"=")?d.match("[#&]"+a+"=([^&]*)"):(b?b.match(/(\?|$)[^#]*/)[0]:window.location.search).match("[?&]"+a+"=([^&]*)"))?c[1]:i};
google.nav={go:D,search:function(a,b){var c=E().match(/[?&][\w\.\-~]+=([^&]*)/g),d={};if(c)for(var e=0,f;f=c[e++];){f=f.match(/([\w\.\-~]+?)=(.*)/);var g=f[2];d[f[1]]=g}for(f in a)a.hasOwnProperty(f)&&(g=a[f],g==i?delete d[f]:d[f]=g);c=["/search?"];e=!0;for(f in d)d.hasOwnProperty(f)&&(c.push((e?"":"&")+f+"="+d[f]),e=!1);D(c.join(""),h,b)},getLocation:E,getLocationHash:F,getParam:G,getQuery:function(){return G("q")}};var H=function(){return document.body.dir=="rtl"||document.dir=="rtl"},I=function(a,b,c){var d=c?"":0;if(m.a){if(d=b.replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle&&a.currentStyle[d]||"",!c){if(!/^-?\d/.test(d))return 0;c=a.style.left;a.style.left=d;d=a.style.pixelLeft;a.style.left=c}}else{a=document.defaultView&&document.defaultView.getComputedStyle(a,"");if(m.b&&!a)return d;d=a.getPropertyValue(b);d=c?d:parseInt(d,10)}return d},J=function(a){var b;m.a?(b=a.style.pixelWidth||
0,b||(b=a.offsetWidth-I(a,"paddingLeft")-I(a,"paddingRight")-I(a,"borderLeft")-I(a,"borderRight"),b<0&&(b=0))):b=I(a,"width");return isNaN(b)?0:b},K=function(a){return a.offsetTop+(a.offsetParent?K(a.offsetParent):0)},L=function(a){return a.offsetLeft+(a.offsetParent?L(a.offsetParent):0)},M=function(a,b){return!a||!b?!1:RegExp("(^|\\s)"+b+"($|\\s)").test(a.className)};
google.style={getComputedStyle:I,getHeight:function(a){var b=I(a,"height");m.a&&!b&&(b=a.offsetHeight-I(a,"paddingTop")-I(a,"paddingBottom")-I(a,"borderTop")-I(a,"borderBottom"),b<0&&(b=0));return isNaN(b)?0:b},getWidth:J,getPageOffsetTop:K,getPageOffsetLeft:L,getPageOffsetStart:function(a){return L(a)+(H()?J(a):0)},getColor:function(a){return String(I(a,"color",!0))},hasClass:M,isRtl:H,addClass:function(a,b){if(a&&b&&!M(a,b)){var c=a.className==""?[]:a.className.split(/\s/);c.push(b);a.className=
c.join(" ")}},removeClass:function(a,b){if(M(a,b)){for(var c=a.className.split(/\s/),d=c.length-1;d>=0;d--)c[d]==b&&c.splice(d,1);a.className=c.join(" ")}}};var N={},O=["&","&amp;","<","&lt;",">","&gt;",'"',"&quot;","'","&#39;","{","&#123;"],P=function(a){return m.a?window.event.srcElement:a.target},S=function(a){!a||m.a?window.event.cancelBubble=!0:a.stopPropagation&&a.stopPropagation()},T=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},U=function(a,b){S(b);var c=document.getElementById(a);if(c)c.style.display=="none"?(c.style.display=
"",N[a]=T(U,a),google.listen(document.body,"click",N[a])):(c.style.display="none",N[a]&&google.unlisten(document.body,"click",N[a]))};
google.util={escape:function(a){for(var b=0;b<O.length;b+=2)a=a.replace(RegExp(O[b],"g"),O[b+1]);return a},unescape:function(a){for(var b=0;b<O.length;b+=2)a=a.replace(RegExp(O[b+1],"g"),O[b]);return a},eventTarget:P,stopPropagation:S,getSelection:function(){return window.getSelection&&window.getSelection().toString()||document.selection&&document.selection.createRange&&document.selection.createRange().text},xjsol:function(a){if(google.sc&&(a=google.sc[a])){for(var b=0;b<a.cb.length;b++)a.cb[b]();
a.cb=[]}},xjsl:function(a,b){var c=google.sc[a];if(c)c.dl?b&&b():(b&&c.cb.push(b),google.dlj(c.u),c.dl=!0)},togglePopup:U,rateLimitFunction:function(a,b,c,d){var e=0,f=!1,g=i;return function(){var j=google.time();f?g=Array.prototype.slice.call(arguments,0):j-e>=c?(e=j,b.apply(a,arguments)):d&&(j=c-(j-e),f=!0,g=Array.prototype.slice.call(arguments,0),setTimeout(function(){f=!1;e=google.time();b.apply(a,g)},j))}}};var V=function(a,b,c){var d=RegExp("([?&])"+b+"=.*?(&|$)"),a=a.replace(/^([^#]*)(#|$)/,function(a,b){return b});return!a.match(d)&&c!=""?a+"&"+b+"="+c:a.replace(d,function(a,d,g){return c?d+b+"="+c+g:g?d:""})};
google.srp={isSerpLink:function(a){return/(search|images)/.test(a.href)},isSerpForm:function(a){return/\/search$/.test(a.action)},updateLinksWithParam:function(a,b,c,d){var e=document.getElementsByTagName("A");google.base_href=V(google.base_href,a,b);for(var f=0,g;g=e[f++];)if(c(g)){var j=m.a?g.innerHTML:h;g.href=V(g.href,a,b);if(j!=h)g.innerHTML=j}for(f=0;c=document.forms[f++];)if(d(c)){for(g=e=0;j=c.elements[g++];)if(j.name==a)e=1,b!=""?j.value=b:j.parentNode.removeChild(j);if(!e&&b!="")e=document.createElement("input"),
e.type="hidden",e.value=b,e.name=a,c.appendChild(e)}},qs:function(a){if(a=P(a)){for(;!M(a,"qs");)if(a=a.parentNode,!a||a==document.body)return;var b=document.getElementsByName("q"),c=b&&b[0],b=document.getElementById("tsf-oq");if(c&&b&&window.n&&(c=c.value,b=x(b),c&&c!=b))b=V(a.href,"q",encodeURIComponent(c)),a.href=V(b,"prmd","")}}};google.xhr=function(){var a=i;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(b){}if(!a)for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,e;e=c[d++];)try{a=new ActiveXObject(e);break}catch(f){}return a};})();
(function(){var e=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};var f=function(){},j=function(a,b,c){switch(typeof b){case "string":i(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==null){c.push("null");break}if(e(b)=="array"){var h=b.length;c.push("[");for(var d="",g=0;g<h;g++)c.push(d),j(a,b[g],c),d=",";c.push("]");break}c.push("{");h="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(g=b[d],typeof g!="function"&&(c.push(h),i(d,c),c.push(":"),
j(a,g,c),h=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}},k={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},l=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,i=function(a,b){b.push('"',a.replace(l,function(a){if(a in k)return k[a];var b=a.charCodeAt(0),d="\\u";b<16?d+="000":b<256?d+="00":b<4096&&(d+="0");return k[a]=d+b.toString(16)}),'"')};var m=[],n="/",o,p;function q(){var a=o.value;p=a?eval("("+a+")"):{}}var r=[];google.History={addPostInitCallback:function(a){r.push(a)},client:function(a){m.push(a);return m.length-1},initialize:function(a){n=a;p=null;if(o=document.getElementById("hcache")){q();for(a=0;a<m.length;++a)p&&p[n]&&p[n][a]&&m[a].call(null,p[n][a]);for(var a=0,b;b=r[a++];)b();r=[]}},save:function(a,b){if(o)q(),p[n]||(p[n]={}),p[n][a]=b,o.value=google.stringify(p)}};google.stringify=function(a){var b=[];j(new f,a,b);return b.join("")};})();
(function(){var f=0,h=0,i=[];function k(b){return b}
function l(){++h;for(var b=0,c;c=i[b++];){var g=google.time()-c.e;if(g>=c.c||c.a){for(var e=0,a=void 0;a=c.d[e++];)google.dom.set(a[0],a[1],a[6]?"rgb("+a[3].join(",")+")":a[3]+a[5]);c.a=!0;c.b&&c.b();c=0}else{for(e=0;a=c.d[e++];){var d=a[4](g/c.c);google.dom.set(a[0],a[1],(a[6]?"rgb("+[m(a[2][0],a[3][0],d,!0),m(a[2][1],a[3][1],d,!0),m(a[2][2],a[3][2],d,!0)].join(",")+")":m(a[2],a[3],d,a[5]=="px"))+a[5])}c=1}c||i.splice(--b,1)}i.length||(window.clearInterval(f),f=0)}
function m(b,c,g,e){b+=(c-b)*g;return e?Math.round(b):b}function n(b){for(var b=b.match(/#(..)(..)(..)/).slice(1),c=0;c<3;++c)b[c]=parseInt(b[c],16);return b}
google.fx={animate:function(b,c,g){for(var e=0,a;a=c[e++];){var d=typeof a[2]=="string";d?(a[2]=n(a[2]),a[3]=n(a[3]),a[5]=""):a[5]=a[5]==null?"px":a[5];a[4]=a[4]||k;a[6]=d;google.dom.set(a[0],a[1],d?"rgb("+a[2].join(",")+")":a[2]+a[5])}var j={c:b,b:g,e:google.time(),d:c};i.push(j);f=f||window.setInterval(l,15);return{finish:function(){if(!j.a)j.a=!0,l()}}},easeInAndOut:function(b){return(3-2*b)*b*b},easeOut:function(b){return 1-Math.pow(1-b,3)},getFrameCount:function(){return h},linear:k,unwrap:function(b){b.parentNode.parentNode.replaceChild(b,
b.parentNode)},wrap:function(b){var c=document.createElement("div");b.parentNode.replaceChild(c,b);c.appendChild(b);return c}};google.register(60,{dispose:function(){window.clearInterval(f);f=0;i=[]}});})();
(function(){google.event=google.event||{};google.event.back={};var d=[],f=[],g;function h(a,c){a&&(g[a]=c);google.save(81,g)}function j(){for(var a=[],c=0,b=d.length;c<b;c++){var e=d[c](g[f[c]]);e&&(a.length>0&&a.push(","),a.push(e))}google.a=1;a.push("&ei=",google.kEI);window.google.log("backbutton",a.join(""))}function k(a,c){return function(b){b=b||window.event;for(b=b.target||b.srcElement;b.parentNode&&b.tagName!="A";)b=b.parentNode;a(b,c?g[c]:null)}}var l=google.j&&google.j.en,m;
function n(a){(a.persisted||m)&&!l&&j();m=!0}google.event.back.register=function(a,c,b,e){e&&(g[e]={});for(var o=document.getElementsByTagName("a"),p=0,i;i=o[p++];)a(i)&&google.listen(i,"click",k(c,e));d.push(b);f.push(e)};google.event.back.saveHistory=h;
google.register(81,{init:function(){g={persisted:!1};google.a=0},history:function(a){a&&(g=a);if(g.persisted)j();else if(!g.persisted)g.persisted=!0,h(),window.addEventListener&&(window.addEventListener("pageshow",n,!1),m=!1)},dispose:function(){d.length=0;f.length=0}});})();
(function(){var h=null;var j=google.browser.engine,ba=j.IE&&google.browser.engine.version<=6,ca=google.browser.product.OPERA,k,da,ea=!1,fa,l,m,n,ga,o,ha=RegExp("^[\0- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$"),ia=RegExp("^[\0- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*([0-9][\0- !-@[-`{-\u00bf\u00d7\u00f7\u02b9-\u02ff\u2000-\u2bff]*$|[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufdfe-\ufe6f\ufefd-\uffff])"),ja,ka,la,ma,na,oa,p,pa,qa,sa,ta,q,ua,r,s,va,t=
"",wa=h,xa,u=h,v=h,w=-1,z,A,B,C,D,E,H,I,ya,za,J,Aa,Ba={},Ca,K=0,L=0,Da=!1,M=h,P=0,Ea,Fa,Ga=0,Q;var T=h,U=0;var Ha=!1,Ia=h;function Ja(a){return(a=a[a.length-1])?a.d:h}function Ka(a){return(a=a&&a.match(/\D+$/))?a[0]:h}var La={0:"hp",1:"serp",2:"img",3:"hp"},W;
function Ma(a){(document.getElementById("main")||document.getElementById("xjsc")||document.body).appendChild(a)}function Na(){Oa();X();if(z){I.value=ya.value=za.value=J.value="";window.clearTimeout(wa);l&&(window.clearInterval(Ia),Ia=h);t=Fa=Ca="";wa=u=v=h;w=-1;W=K=L=P=0;Ba={};Q=Ga=0;T=h,U=0;}}
function Pa(a,b){W=0;a=="i"?W=2:b&&b!=""?W=1:window.location.hostname=="partnerpage.google.com"&&(W=3)}
function Qa(){function a(a,c){b.push(a,"{",c,"}")}var b=[];q?(a(".gac_od","background:#fff;margin:0;z-index:99;border-top:0;border-left:0;border-right:1px solid #e7e7e7;border-bottom:1px solid #e7e7e7;padding:0!important;position:absolute;zoom:1"),a(".gac_id","background:#fff;margin:0;z-index:99;border-top:1px solid #a2bff0;border-left:1px solid #a2bff0;border-right:1px solid #558be3;border-bottom:1px solid #558be3;display:block"),a(".gac_m","background:#fff;margin:0;z-index:99;border:0;color:#000;cursor:default;display:block;font-size:17px;line-height:117%;padding:0;position:relative;zoom:1")):
a(".gac_m","background:#fff;border:1px solid #666;color:#000;cursor:default;font-size:17px;line-height:117%;margin:0;position:absolute;z-index:99");a(".gac_m td","line-height:22px");a(".gac_n","padding-top:1px;padding-bottom:1px");a(".gac_b td.gac_c","background:#d5e2ff");ca&&a(".gac_b td.gac_d","background:#d5e2ff");a(".gac_b","background:#d5e2ff");a(".gac_a td.gac_f","background:#fff8dd");a(".gac_t","width:100%;text-align:left;font-size:17px");a(".gac_bt","width:"+(A.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px;position:relative");
a(".gac_sb","font-size:15px;height:28px;margin:0.2em"+(j.WEBKIT?";-webkit-appearance:button":""));a(".gac_z","white-space:nowrap;color:#c00");a(".gac_s","height:3px;font-size:1px"+(j.IE?";row-height:1px":""));var c=["white-space:nowrap;","overflow:hidden;","text-align:left;","padding-left:",q?7:3,"px;","padding-right:3px"];(j.IE||ca)&&c.push(";padding-bottom:1px");a(".gac_c",c.join(""));a(".gac_p","white-space:nowrap;padding:3px;line-height:112%;vertical-align:top");a(".gac_e",
"text-align:right;padding:0 3px");a(".gac_d","font-size:11px");a(".gac_h","color:green");a(".gac_j","display:block");a(".gac_l","line-height:18px");a(".gac_x","display:block;line-height:16px");a(".gac_y","font-size:13px");a(".gac_i","color:#666");a(".gac_w img","width:40px;height:40px");a(".gac_w","width:1px");a(".gac_r","color:red");a(".gac_v","padding-bottom:5px");c=document.createElement("style");c.setAttribute("type","text/css");Ea.appendChild(c);b=b.join("");j.IE?c.styleSheet.cssText=
b:c.appendChild(document.createTextNode(b))}
function Ra(){if(E){var a;a=k;for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;try{a=a.offsetParent}catch(d){a=h}}a={G:b,F:c};H.left=a.F+"px";a=a.G+k.offsetHeight+da;q&&W==1&&a++;H.top=a+"px";a=Math.max(0,k.offsetWidth-(q?1:0));q&&!ba?H.minWidth=a+"px":H.width=a+"px";if(u&&(b=Y(0))&&a-12>=0)b.firstChild.style.width=a-12+"px";}}
function Z(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return z.appendChild(c)}function Sa(a){var b=a.keyCode;if(b==27&&Ta())return X(),$(s),a.cancelBubble=!0,a.returnValue=!1;if(b==13)return Ua(!1),a.cancelBubble=!0,a.returnValue=!1;if(b==38||b==40){L++;L%3==1&&Va(b);if(j.WEBKIT)a.cancelBubble=!0,a.returnValue=!1;return!1}}
function Ua(a){!j.IE&&!a&&Aa&&(z.removeChild(Aa),Aa=h);if(v&&w!=-1&&Da&&(!a||!v.H))v.onclick(h);else A.value==""?X():(a&&(Aa=Z("btnI","1")),Wa())}function Wa(){Xa();z.onsubmit&&z.onsubmit()==!1||z.submit()}function Ya(a){var a=a.keyCode,b=a==38||a==40;!L&&(!l||!b)&&Va(a);L=0;return j.WEBKIT?!b:!1}
function Va(a){if(l&&(a==38||a==40))Ha=!0,A.blur(),window.setTimeout(function(){A.focus()},10);if(A.value!=r)s=A.value,Q=Za(),J.value=s;if(a==40||a==38)l&&(Ha=!0,A.blur(),window.setTimeout(function(){A.focus()},10)),$a(a==40),Da=Ta();Ra();t!=s&&!M&&(M=window.setTimeout(X,500));r=A.value}function ab(){Da=!1;if(!P){if(v)v.className="gac_a";v=this;for(var a=0,b;b=Y(a);a++)b==v&&(w=a);v.className="gac_b"}}
function bb(a,b){return function(c){var d=cb(a),e=window.frames.wgjf;e&&!b?(google.r=1,e.location.replace(d)):window.location=d;db(c);return!1}}function cb(a){return[a,"&aq=",v.v,"&oq=",J.value,eb("aqi",ya),eb("aql",za)].join("")}
function eb(a,b){return b&&b.value.length&&a.length?["&",a,"=",b.value].join(""):""}function fb(){l&&j.GECKO&&A.blur();try{A.blur()}catch(a){}$(this.j);Wa();}
function $a(a){if(!(s!=t||!u||!u.length))if(Ta()){if(v)v.className="gac_a";for(var b=u.length,c=(w+1+(a?1:b))%(b+1)-1;c!=-1&&Y(c).A;)c=(c+1+(a?1:b))%(b+1)-1;w=c;w==-1?gb():(v=Y(c),v.className="gac_b",$(v.j),I.value=v.v)}else hb()}function gb(){A.focus();$(s);v=h;I.value="f"}function X(){M&&(window.clearTimeout(M),M=h);H&&(H.visibility="hidden");}
function hb(){H&&(H.visibility="visible");Ra();P=1}function Ta(){return!!H&&H.visibility=="visible"}function Oa(){if(D)if(j.IE)for(;D.rows.length;)D.deleteRow(-1);else D.innerHTML=""}function ib(a,b,c){a.onclick=b?bb(b,c):fb;a.H=!b;a.onmousedown=jb;a.onmouseover=ab;a.onmousemove=function(){P&&(P=0,ab.call(this))}}
function kb(a){for(var b=0,c;c=Y(b++);)if(Ka(c.v)=="p"&&c.j==a[0]){c.A=1;c.onclick=c.onmouseover=h;if(c==v)c.className="gac_a",w=-1,gb();c.B.className="gac_c gac_i fl";c.B.innerHTML="该搜索已从您的\x3ca href\x3d\x22/history\x22\x3e网络历史记录\x3c/a\x3e中删除"}}
function lb(a){function b(a,b){var c=b?Ka(b[2]):h,c=a+(c?"-"+c:"");c!=e&&(f&&(d+=e+f),f=0,e=c);f++}var c=a[0];K>0&&K--;xa=Ja(a)||0;if(D&&c==s){M&&(window.clearTimeout(M),M=h);t=a[0];Oa();for(var d="",e,f=0,g=a[1],i=g.length-1,c=!1,F=0,aa,N,ra,O,x,G,y;F<=i;F++)if(y=g[F])if(aa=y[1],x=Ba[aa])x.D&&x.D(F,i)&&mb(),N=y[2],ra=y[3],O=x.k?x.k(y,ra):h,G=D.insertRow(-1),ib(G,O,x.C),G.v=N,G.className="gac_a",O=G.B=document.createElement("td"),
O.className="gac_c",x.b(O,N,y,ra),N=x.m,G.j=N?N(y,ra,t):y[0],G.appendChild(O),b(x.a,y),F<i&&x.I&&mb(),!c&&aa!=30&&!nb(y)&&(c=!0);za.value=ob(a)||"";(u=D.rows)&&u.length>0?(g=W==0,m=u.length<10,g&&pb(),(g||W==1)&&(p||oa)&&qb(),hb()):(X(),m=!0);if(c||!ua)m=!1;m&&!n&&(n=t,ga=a);b("");ya.value=d;w=-1}}
function qb(){var a=mb(),b=a.style;b.textAlign="right";b.fontSize="12px";b.paddingRight="5px";var b="fr",c="En savoir plus";if(p)b=google.kHL,c="了解详情";a.innerHTML=['<a href="http://www.google.com/support/websearch/bin/answer.py?hl=',b,'&answer=106230">',c,"</a>"].join("")}
function rb(a){var a=a.replace(/<\/?(b|em)>/gi,""),b=s.replace(/^\s+|\s+$/g,"").replace(/\s\s+/g," ");if(!a.indexOf(b))return[b,"<b>",a.substr(b.length),"</b>"].join("");for(var c=[],b=[],d=a.length-1,e=0,f=-1,g;g=a.charAt(e);++e)g==" "||g=="\t"?c.length&&(b.push({t:c.join(""),z:f,w:e+1}),c=[],f=-1):(c.push(g),f==-1?f=e:e==d&&b.push({t:c.join(""),z:f,w:e+1}));c=s.split(/\s+/);e={};for(d=0;f=c[d++];)e[f]=1;g=-1;for(var c=[],i=b.length-1,d=0;f=b[d];++d)e[f.t]?(f=g==-1,d==i?c.push({z:f?d:g,w:d}):f&&
(g=d)):g>-1&&(c.push({z:g,w:d-1}),g=-1);if(!c.length)return["<b>",a,"</b>"].join("");d=[];for(e=f=0;g=c[e];++e)(i=b[g.z].z)&&d.push("<b>",a.substring(f,i-1),"</b> "),f=b[g.w].w,d.push(a.substring(i,f));f<a.length&&d.push("<b>",a.substring(f),"</b> ");return d.join("")}function Y(a){return j.IE?u[a]:u.item(a)}
function sb(a){var b="gac_sb",c="",d="";q&&(b="lsb",c="<span class=ds><span class=lsbb>",d="</span></span>");return[c,'<input type=button value="',a?"\x26nbsp;手气不错\x26nbsp;":"Google 搜索",'" class=',b,j.IE?' style="padding:0 6px;width:auto;overflow:visible"':"",' onclick="google.ac.rd(',a,')">',d].join("")}
function pb(){var a=D.insertRow(-1);a.A=1;a.onmousedown=jb;var b="";if(p||oa)b=' style="padding-bottom:0"';a.insertCell(0).innerHTML=['<div style="position:relative"><div class=gac_bt',b,">",sb(!1),sb(!0),"</div></div>"].join("")}function tb(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}
function db(a){if(a=a||window.event)(j.GECKO||j.WEBKIT)&&a.stopPropagation(),a.cancelBubble=a.cancel=a.returnValue=!0}function mb(){var a=D.insertRow(-1);a.A=1;a.onmousedown=jb;a=a.insertCell(0);a.className="gac_s";return a}
function Xa(){X();if(u&&Y(w)&&J.value!=A.value)I.value=Y(w).v;else if(J.value="",I.value="f",K>=10||U>=3)I.value="o"}
function vb(){if(U>=3)return;if(s&&va!=s){if(m&&(s.indexOf(n)!=0||s.substr(s.length-1)==" "))m=!1,n="";if(m){var a=lb,b=[];b[0]=s;for(var c=[],d=ga[1],e=d.length,f=0,g,i;f<e;++f)if(i=d[f])g=i[1],g==30?c.push([i[0]+s.substr(n.length),30,i[2]]):nb(i)&&c.push([rb(i[0]),g,i[2],i[3]]);b[1]=c;(c=ob(ga))&&(b.e=c);a(b)}else K++,wb(Ca,"q",s,lb),A.focus()}va=s;a=100;for(b=1;b<=(K-2)/2;b++)a*=2;a+=50;a<xa&&(a=xa);wa=window.setTimeout(vb,a)}
function xb(){for(var a=["&gs_gbg="],b=4+Math.floor(Math.random()*32),c=0,d;c<b;++c)d=Math.random()<0.3?48+Math.floor(Math.random()*10):(Math.random()>0.5?65:97)+Math.floor(Math.random()*26),a.push(String.fromCharCode(d));return a.join("")}function ob(a){return(a=a[a.length-1])?a.e:h}function nb(a){o.innerHTML=a[0];return!google.dom.getText(o).indexOf(s)}
function wb(a,b,c,d){yb(a,encodeURIComponent(c),d);}function $(a){if(A)A.value=r=a}function jb(a){j.GECKO||j.WEBKIT?a.stopPropagation():ca&&(hb(),A.focus());Ga=1;return!1}
var zb=function(){var a=h;if(j.IE)try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}else typeof XMLHttpRequest!="undefined"&&(a=new XMLHttpRequest);return a},yb=function(a,b,c){T&&T.readyState!=0&&T.readyState!=4&&T.abort();if(T)T.onreadystatechange=function(){};if(T=zb())T.open("GET",[a,"&xhr=t&q=",b,"&cp=",Q].join(""),!0),T.onreadystatechange=function(){if(T.readyState==4)switch(T.status){case 403:U=1E3;break;case 302:case 500:case 502:case 503:U++;
break;case 200:c(eval(T.responseText));default:U=0}},T.send(h)};function Za(){var a=A,b=0,c=0;if(j.IE){var a=a.createTextRange(),d=document.selection.createRange();if(a.inRange(d))a.setEndPoint("EndToStart",d),b=a.text.length,a.setEndPoint("EndToEnd",d),c=a.text.length}else{try{d=typeof a.selectionStart=="number"}catch(e){d=!1}if(d)b=a.selectionStart,c=a.selectionEnd}return b&&c&&b==c?b:0}
function Ab(a){"c"in a&&(ja=a.c);"ca"in a&&(ua=a.ca);"d"in a&&(qa=a.d);"f"in a&&(oa=a.f);"l"in a&&(ka=a.l);"lm"in a&&(p=a.lm);"n"in a&&(la=a.n);"o"in a&&(ma=a.o);W==2?na=!1:"p"in a&&(na=a.p);"s"in a&&(pa=a.s);"sw"in a&&(q=a.sw);if("he"in a){var b=document.getElementById(a.he);b&&(k=b)}"vc"in a&&typeof a.vc=="number"&&(da=a.vc)}function Bb(){var a=[Cb];ja&&a.push(Db);ka&&a.push(Eb);la&&a.push(Fb);ma&&a.push(Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb);na&&a.push(Qb);for(var b=0,c;c=a[b++];)Ba[c.g]=c}
function Rb(a,b,c){var d=b[0];a.innerHTML=d;b.j=google.dom.getText(a);if(c){a.className="";a.innerHTML=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td class=gac_c>",d,'<td class="gac_d gac_e fl">',c,"</table>"].join("");}}
function Sb(a){var b=function(){var b=a.value,d="";ia.test(b)?d="ltr":ha.test(b)||(d="rtl");a.dir=d};ca?window.setInterval(b,50):(google.listen(a,"propertychange",b),google.listen(a,"input",b));b()}
var Lb={g:11,a:"b",C:!0,k:function(a,b){return b[0]},b:function(a,b,c,d){var b=d[0],c=d[1],e=d[2],f=d[3],g=d[4],i=d[5],F=d[6],d=d[7],aa=b.match(/^([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a class=q ',tb(aa,b),"><b>",c,"</b> - ",e," (",f,")</a><br><b>",g,"</b> <span class=gac_y><span class=gac_",i>=0?"h":"r",">",i," (",F,"%)</span> ",d,' - </span><a href=/help/stock_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a></span>'].join("")}},Mb={g:12,a:"c",
k:function(a,b){return b[0]},b:function(a,b,c,d){for(var b=d[0],c=d[1],d=d[2],e="",f=d.length-1,g=0,i;g<f;g++)i=d[g],e+=[i[0],'<div class="gac_v">',i[1],"</div>"].join("");i=d[f];e+=[i[0],"<br>",i[1]].join("");Tb(a,c,b,"www.flightstats.com",e)}},Nb={g:15,a:"d",b:function(a,b,c,d){a.innerHTML=["<b>",d[0],"</b> ",d[2]," (",d[1],") in <b>",d[3],"</b>"].join("")}},Ob={g:13,a:"e",k:function(a,b){return b[0]},b:function(a,b,c,d){Tb(a,d[1],d[0],d[2])}},Hb={g:14,a:"f",k:function(a,b){return b[0]},b:function(a,
b,c,d){Tb(a,d[1],d[0],d[3],d[2])}},Cb={g:0,a:"g",m:function(a){return a.j},b:function(a,b,c){Rb(a,c,"")}},Ib={g:19,a:"h",b:function(a,b,c,d){a.innerHTML=["<b>",d[0]," = ",d[1],"</b>"].join("")}},Gb={g:17,a:"i",k:function(a,b){return b[3]},b:function(a,b,c,d){var b=d[0],c=d[1],e=d[2],d=d[3],f=d.match(/url=([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a ',tb(f,d),">",b," &#151; ",c,": ",e,'</a><span class=gac_y style="line-height:16px"><br>According to <span class=gac_h>',f,"</span></span></span>"].join("")}},
Pb={g:10,a:"j",b:function(a,b,c,d){b=d[5];c=function(a){var b=a[1];return['<td class=gac_w><img src="',a[0],'" alt="',b,'" title="',b,'"><td class="gac_p">',a[4],"<br>",a[2],"&deg; | ",a[3],"&deg;"].join("")};a.innerHTML=["<b>Weather:</b> ",d[4],"&deg;",d[1]," in ",d[0],"<br><table><tr>",c(b[0]),c(b[1]),c(b[2]),c(b[3]),"</table>"].join("")}},Jb={g:20,a:"k",b:function(a,b,c,d){a.innerHTML=["<b>",d[0]," = ",d[1],'</b> - <a href=/intl/en/help/currency_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a>'].join("")}},
Kb={g:16,a:"l",m:function(a,b){return"define: "+b[0]},b:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Tb(a,"Web definitions for <b>"+b+"</b>","/search?q=define:"+b.replace(" ","+"),"www.google.com",[c," - <span class=gac_i>",d,"</span>"].join(""))}},Eb={g:30,a:"m",m:function(a){return a.j},b:function(a,b,c){b=c[0];o.innerHTML=b;c.j=google.dom.getText(o);a.innerHTML=["<span class=gac_z>Did you mean: </span>",b].join("")}},Fb={g:5,a:"n",m:function(a,b,c){return c},k:function(a,b){return b[0]},b:function(a,
b,c,d){b=d[0];d=d[1];a.className="gac_c gac_n";a.style.lineHeight="117%";var e=c[0],c=e.replace(/HTTPS?:\/\//gi,""),e=e.replace(/<\/?(b|em)>/gi,"");/^HTTPS?:\/\//i.test(e)||(e=(b.indexOf("/url?url=https:")>0?"https":"http")+"://"+e);a.innerHTML=["<span class=gac_x><a ",tb(e,b),">",d,'</a><br><span class="gac_h gac_y"',">",c,"</span></span>"].join("");}},Db={g:32,a:"o",m:function(a){return a.j},
b:function(a,b,c,d){Rb(a,c,['<a href="',d[1],'" onclick="google.ac.p(event);return true">From ES</a>'].join(""))}},Qb={g:35,a:"p",m:function(a){return a.j},b:function(a,b,c){Rb(a,c,["<a href=# onclick=\"return google.ac.dc(event,'",b,"')\">删除</a>"].join(""))}};
function Tb(a,b,c,d,e){var f=c.indexOf("/url")?c:c.match(/url=([^&]*)/)[1];a.style.lineHeight="112%";a.innerHTML=["<a class=q ",tb(f,c),">",b,'</a><span class="gac_y gac_x">',e?e+"<br>":"","",d?"<span class=gac_h>"+d+"</span></span>":""].join("")}
google.ac={c:function(a){return fa?(db(a),!0):!1},d:kb,dc:function(a,b){db(a);for(var c=0,d;d=Y(c++);)if(d.v==b){wb(Fa,"delq",d.j,kb);break}return!1},h:lb,i:function(a,b,c,d,e,f){l=!1;var g=google.kHL;if(g=="zh-TW"||g=="zh-CN"||g=="ja"||g=="ko")l=!0;z=a;A=b;Pa(c,d);da=-1;k=A;qa=!1;ja=!0;ka=!1;la=!0;ma=!1;na=!0;q=p=oa=pa=!1;ua=!0;f&&Ab(f);Bb();s=va=r=A.value;m=!1;n="";xa=0;if(!b.init)Ea=document.getElementsByTagName("head")[0],google.listen(z,"submit",Xa),A.setAttribute("autocomplete","off"),qa&&Sb(b),
a=function(a,b){google.listen(A,a,b)},l?a("blur",function(){Ha?Ha=!1:X()}):a("blur",X),j.IE?(A.onbeforedeactivate=function(){if(Ga)return Ga=0,!1},a("keydown",Sa),a("keyup",Ya)):j.GECKO?(A.onkeypress=Sa,a("keyup",Ya)):j.WEBKIT?(a("keydown",Sa),A.onkeyup=Ya,A.setAttribute("spellcheck",!1)):(a("keypress",Sa),a("keyup",Ya)),I=Z("aq","f"),ya=Z("aqi",""),za=Z("aql",""),J=Z("oq",s),E=D=document.createElement("table"),D.cellSpacing=D.cellPadding="0",H=D.style,D.className="gac_m",q?(E=B=document.createElement("div"),
B.className="gac_od",H=B.style,Ma(B),C=document.createElement("div"),C.cellSpacing=B.cellPadding="0",C.className="gac_id",B.appendChild(C),C.appendChild(D)):z.appendChild(D),o=document.createElement("div");b.init=!0;X();Ra();ea||(Qa(),ea=!0);b="&client="+La[W];a=google.authuser;
c=["?hl=",google.kHL,a?"&authuser="+encodeURIComponent(String(a)):"",b,c?"&ds="+c:"",d?"&pq="+encodeURIComponent(d):"",e?"&tok="+encodeURIComponent(e):""].join("");Ca="/complete/search"+c;Fa="/complete/deleteitems"+c;Q=Za();j.GECKO&&google.listen(window,"pageshow",function(a){if(a.persisted)I.value="f",J.value=A.value});l&&(Ia=window.setInterval(function(){var a=
A.value;a!=r&&Va(0);r=a},10));vb();ta="https:"==document.location.protocol;sa=["http",pa||e&&e.length||ta?"s":"","://"].join("");},p:db,r:function(a,b,c){a=a||window.event;fa=!1;a.which?fa=a.which==2:a.button&&(fa=a.button==4);b.href=cb(c)},rd:Ua,u:$};google.listen(window,"resize",Ra);google.dstr&&google.dstr.push&&google.dstr.push(Na);})();
(function(){window.ManyBox={};var e,g,h=1,j=google.History.client(i),k=[],l;window.ManyBox.delayedRegister=function(a){k.push(a)};function n(a){for(var b in e)if(e[b].b&&a(e[b]))break}function p(a,b,c,d,f){this.b=a;this.v=b;this.s=d;this.o=f;this.m="/mbd?jsid="+a+(b?"&docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+d+"&usg="+c+"&hl="+(google.kHL||"");this.g={};this.z={};g[a]={open:0,content:this.g,doc:this.v,sent:0};this.n=0}
p.prototype.append=function(a){for(var b=0;b<a.length;++b){var c=a[b].split("=");this.z[c[0]]=c[1]}};function q(a){var b="",c;for(c in a.z)b=[b,"&",c,"=",a.z[c]].join("");return b}function r(a,b){return document.getElementById("mb"+b+a.b)}function s(a,b){a.i.style.paddingTop=b+"px";a.i.style.display=a.i.innerHTML?"":"none";if(b>a.n)a.n=b;a.j.style.fontSize=b+"px";a.j.style.fontSize=null}
function t(a){if(!a.J)a.J=1,a.d=r(a,"b"),a.d?(a.k=0,a.a=r(a,"l"),a.a?(a.j=a.a.getElementsByTagName("DIV")[0],a.p=a.a.getElementsByTagName("A")[0],a.B=a.p.innerHTML,a.o=a.o||a.B,a.j.title=l&&l.m_tip,a.a.I=function(b,c){var d=google.style.getPageOffsetStart(a.a),f=google.style.getPageOffsetTop(a.a);return b>d-5&&b<d+google.style.getWidth(a.a)+5&&c>f-5&&c<f+google.style.getHeight(a.a)+5},a.i=r(a,"f"),s(a,0),a.a.onmousedown=u(a),a.a.onclick=w(a),a.a.go=function(){a.a.onmousedown();a.a.onclick()}):delete e[a.b]):
delete e[a.b]}function x(a){google.log("manybox",[a.k?"close":"open","&id=",a.b,"&docid=",a.v,"&mbtype=",a.s,q(a)].join(""))}function y(a,b){var c=google.xhr();if(c)c.open("GET",a.m+q(a)+"&zx="+google.time()),a.w=0,c.onreadystatechange=function(){z(a,c,b)},a.w=1,c.send(null)}
function z(a,b,c){if(b.readyState==4){var d=0;if(b.status==200)try{eval(b.responseText),d=1}catch(f){}!d&&!a.K?(g[a.b].sent=0,a.K=1,a.m+="&cad=retry",y(a,c)):(c?(r(a,"cb").parentNode.innerHTML=a.g.h,A(a)):a.A&&B(a),a.w=0)}}function C(a){g[a.b].sent?a.L++<3&&x(a):(a.g.h?x(a):y(a,!1),g[a.b].sent=a.L=1)}function D(a){g[a.b].sent||C(a);(a.A=a.w)||B(a)}function u(a){return function(){C(a)}}
function w(a){return function(){D(a)}}
function E(a){if(!a.g.h){if(l&&l.m_errors)if(l.m_errors[a.s])a.g.h=l.m_errors[a.s];else if(l.m_errors["default"])a.g.h=l.m_errors["default"];a.H=a.a.onclick;a.a.onclick=function(){h=0;B(a);h=1;a.c.parentNode.removeChild(a.c);g[a.b].sent=a.g.h=a.D=0;a.a.onclick=a.H}}if(!a.D){a.D=1;var b=document.getElementById("res");a.F=b&&google.style.getPageOffsetStart(a.d)>google.style.getPageOffsetStart(b)+google.style.getWidth(b);a.c=document.createElement("div");s(a,0);a.c.style.position="absolute";a.c.style.paddingTop=
a.c.style.paddingBottom="6px";a.c.style.display="none";a.c.className="med";b=document.createElement("div");a.c.appendChild(b);b.className="std";b.innerHTML=a.g.h;a.i.parentNode.insertBefore(a.c,a.i)}}function i(a){h=0;F();n(function(b){b.v==a[b.b].doc?(b.g=a[b.b].content,a[b.b].open!=b.k&&B(b)):a[b.b].sent=0});g=a;h=1;google.History.save(j,g)}
window.ManyBox.create=function(a,b,c,d,f){return new p(a,b,c,d,f)};window.ManyBox.register=function(a,b,c,d,f){return e[a]=window.ManyBox.create(a,b,c,d,f)};google.listen(document,"click",G);
function G(a){for(var a=a||window.event,b=a.target||a.srcElement;b.parentNode;){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}var c=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;n(function(a){if(a.a.I(c,d))return a.a.go(),1})}function H(){e={};g={};k=[]}H();function F(a){a&&(l=a);for(a=0;a<k.length;a++)try{k[a].func()}catch(b){delete e[k[a].b]}k=[];n(t)}
function I(a,b){a.c.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}p.prototype.insert=function(a){this.g.h=a};p.prototype.loadManyboxData=function(){C(this)};p.prototype.toggleManyboxState=function(){D(this)};p.prototype.updateManybox=function(){y(this,!0)};function A(a){a.e=r(a,"cb");var b=a.e&&a.e.getAttribute("mbopen");b&&(eval(b),a.onopen(a.e))}function J(a){if(!a.e)a.e=r(a,"cb");var b=a.e&&a.e.getAttribute("mbpreopen");b&&(eval(b),a.onpreopen(a.e))}
function K(a,b,c,d,f){var o=c>0?150:75,m=google.time()-f,o=m<o&&h?m/o*c:d>1?c-10:c,m=Math.max(a.u,b+o),v=m-a.u;I(a,v);a.d.style.height=m<0?0:v?m+"px":"";s(a,Math.max(0,v-5));Math.abs(o)<Math.abs(c)?window.setTimeout(function(){K(a,b,c,d-1,f)},30):window.setTimeout(function(){c<0?(a.c.style.display="none",a.j.style.backgroundPosition="-153px -70px",a.p.innerHTML=a.B,a.k=g[a.b].open=0,google.History.save(j,g)):A(a);if(!google.browser.engine.IE&&a.F)a.c.style.width="100px";a.c.style.position=
a.d.style.height="";s(a,0);google.msg.send(48);a.d.C=0},0)}
function B(a){a.A=0;if(!a.d.C){a.d.C=1;var b;if(a.k){if(b=a.e&&a.e.getAttribute("mbclose"))eval(b),a.onclose(a.e);b=a.u-google.style.getHeight(a.d);a.i.style.display="none";s(a,a.n);a.c.style.position="absolute"}else a.u=google.style.getHeight(a.d),E(a),s(a,0),a.n=0,n(function(a){a.j.title=""}),J(a),a.j.style.backgroundPosition="-153px -84px",a.p.innerHTML=a.o,I(a,1),a.c.style.position="absolute",a.c.style.display="",a.k=g[a.b].open=1,google.History.save(j,g),b=a.c.offsetHeight;
K(a,google.style.getHeight(a.d),b,google.browser.product.SAFARI?2:1,google.time())}}google.register(22,{init:F,dispose:H});})();
(function(){var g,i,j,k=google.browser.engine;google.acrs=function(a){for(var a=a.split(/{|}/),c=1;c<a.length;c+=2){var b=a[c-1],d=a[c];if(!g)g=document.createElement("style"),k.IE?(document.getElementById("xjsc").appendChild(g),i=g.styleSheet):(document.getElementsByTagName("head")[0].appendChild(g),i=g.sheet),k.WEBKIT&&!i&&(j=document.createTextNode(""),g.appendChild(j));if(k.IE)for(var b=b.split(","),e=0,f=void 0;f=b[e++];)i.addRule(f,d);else d=b+"{"+d+"}",k.WEBKIT&&!i?j.data+=d:i.insertRule(d,i.cssRules.length)}};var l=null,m=!1,n=!1,o=document.location.href.match("^.*?://[^/]*")[0],p,q;function r(a,c){a.charAt(0)=="["?window.location.replace(document.getElementById("tbpi").href):(q=document.getElementById("tbd"),p=q.innerHTML=a,c||google.Toolbelt.toggle(null,null,!0),google.isr&&google.isr.initialize&&google.isr.initialize())}var s=google.History.client(function(a){r(a.content,a.open==google.Toolbelt.isToolbeltOpen())}),t=google.History.client(function(a){google.acrs(a)});
google.Toolbelt.ascrs=function(a){google.acrs(a);google.History.save(t,a)};var v=[];google.Toolbelt.resetListeners=function(){v=[]};google.register(25,{init:function(){v=[]}});google.Toolbelt.registerToolbeltCallback=function(a){v.push(a)};var w=/([?&])tbo=([^&]*)(&|$)/;function x(a){return(a=a.match(w))?a[2]:""}google.Toolbelt.setCurrentTbo=function(a){return y(a,google.Toolbelt.isToolbeltOpen())};
function y(a,c){var b=mbtb1.obd&&!x(a)?"":"1",d=mbtb1.obd?"0":"",b=c?b:d;return a.replace(w,"$1").replace(/&$/,"")+(b?"&tbo="+b:"")}
google.Toolbelt.updateTbo=function(){var a=google.Toolbelt.isToolbeltOpen(),c=x(google.base_href);if(a!=(mbtb1.obd?c!="0":c!=""&&c!="0")){var b=document.getElementsByTagName("A");google.base_href=y(google.base_href,a);for(var c=0,d;d=b[c++];)if(d.href.match("^("+o+")?/(?!url|aclk|[^?]*$)")&&d!=l&&!d.href.match("[?&]tbo=u(&|$)")){var e=google.browser.engine.IE,f;if(e)f=d.innerHTML;d.href=y(d.href,a);if(e)d.innerHTML=f}for(c=0;f=document.forms[c++];)if(f.action.match("/search$")){for(d=b=0;e=f.elements[d++];)if(e.name==
"tbo")b=1,a?e.value="1":mbtb1.obd?e.value="0":e.parentNode.removeChild(e);if(!b)b=document.createElement("input"),b.type="hidden",b.value=a?"1":"0",b.name="tbo",f.appendChild(b)}}};function z(a){document.body.className=document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.Toolbelt.updateTbo();for(var a=0,c;c=v[a++];)c()}google.Toolbelt.isToolbeltOpen=function(){return/\btbo\b/.test(document.body.className)};
google.Toolbelt.toggle=function(a,c,b){c=c||window.event;a&&(l=a);if(c)google.browser.engine.IE?c.cancelBubble=!0:c.stopPropagation();q=document.getElementById("tbd");if(!q)return!0;p=q.innerHTML;var c=q.getElementsByTagName("DIV").length>0,d=google.Toolbelt.isToolbeltOpen(),b=b||!!document.getElementById("tbt5")||mbtb1.na;if(d&&!n)google.Toolbelt.updateCalendarVisibility&&google.Toolbelt.updateCalendarVisibility(null),A(!1,b),google.log("toolbelt","0&ei="+google.kEI),m=!0;else if(c)A(!0,b),m&&google.log("toolbelt",
"1&ei="+google.kEI);else{mbtb1.insert=r;var e=google.xhr();if(e)e.open("GET",[google.base_href.indexOf("/images?")==0?google.base_href.replace(/^\/images\?/,"/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbm?"&tbm="+mbtb1.tbm:"",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""),!0),e.onreadystatechange=function(){if(e.readyState==4&&e.status==200)try{eval(e.responseText)}catch(b){window.location.replace(a.href)}},
e.send(null),n=!0,A(!0,b);return!1}google.History.save(s,{content:p,open:n||!d});n=!1;google.isr&&google.isr.handleToolbeltToggle&&google.isr.handleToolbeltToggle();return!1};function B(a){for(;a&&!google.style.hasClass(a,"tbt");)a=a.parentNode;return a}google.Toolbelt.ctlClk=function(a,c,b){a=a||"cdr_opt";if(a=="cdr_opt"&&b)google.browser.engine.IE?b.cancelBubble=!0:b.stopPropagation();google.Toolbelt.maybeLoadCal&&google.Toolbelt.maybeLoadCal();c=c||"cdr_min";if(a=document.getElementById(a))if(a.className="tbots",a=B(a)){for(var b=0,d;d=a.childNodes[b++];)if(d.className=="tbos")d.className="tbotu";(c=document.getElementById(c))&&c.focus()}return!1};
google.Toolbelt.cdrClk=google.Toolbelt.ctlClk;google.Toolbelt.cdrSbt=function(){return C("ctbs",{cdr_min:"cd_min",cdr_max:"cd_max"})};google.Toolbelt.clSbt=function(){return C("ltbs",{l_in:"cl_loc"})};google.Toolbelt.prcSbt=function(a,c){C("prcbs",{prc_max:c,prc_min:a});var b=document.getElementById("prc_frm");if(b){var d=document.getElementById("tsf");if(d)b.elements.q.value=d.elements.q.value}};
function C(a,c){var b=document.getElementById(a);if(b)for(var d in c){var e=document.getElementById(d).value.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3"),e=e.replace(/^\s+|\s+$/g,"");b.value=b.value.replace(RegExp("("+c[d]+":)([^,]*)"),"$1"+e)}return!0}google.Toolbelt.tbosClk=function(a){a=a||window.event;if((a=a.target||a.srcElement)&&a.className=="tbotu")if(a.className="tbos",a=B(a))for(var c=0,b;b=a.childNodes[c++];)if(b.className=="tbots")b.className="tbou"};var D=google.fx.easeOut,E=[["tads","margin-left","marginLeft"],["res","margin-left","marginLeft"],["tbd","margin-left","marginLeft"],["mbEnd","width","width"],["tbt3","left","left"],["tbt8","left","left"],["tbt5","margin-left","marginLeft"]],F=!1;function G(a){for(var c=0,b=0,d;d=E[b++];){var e=document.getElementById(d[0]);e&&a(e,d,c++)}}function H(){var a=[];G(function(c,b){var d=b[1];a.push(d=="width"?c.offsetWidth:google.style.getComputedStyle(c,d))});return a}
function A(a,c){if(!F){var b=[],d=H(),e=google.style.getComputedStyle(q,"left",!0),f=document.getElementById("cdr_min"),h=document.getElementById("cdr_max");if(f&&h)f.style.width=google.style.getComputedStyle(f,"width",!0),h.style.width=google.style.getComputedStyle(h,"width",!0);z(a);google.isr&&google.isr.reflowResults&&google.isr.reflowResults();if(!c){if(a&&(e=google.style.getComputedStyle(q,"left",!0),f&&h))f.style.width=google.style.getComputedStyle(f,"width",!0),h.style.width=google.style.getComputedStyle(h,
"width",!0);var I=H();G(function(a,c,e){b.push([a,c[2],d[e],I[e],D])});var u=google.fx.wrap(q);u.style.position="absolute";u.style.overflow="hidden";u.style.left=e;q.style.display="block";q.style.position="static";F=!0;google.fx.animate(a?400:200,b,function(){G(function(a,b){a.style[b[2]]=""});q.style.position="absolute";q.style.display="";google.fx.unwrap(q);if(f&&h)f.style.width="",h.style.width="";F=!1})}}};})();
(function(){try{if(!window.gbar||!gbar.close){window.gbar={};window.gbar.sb=function(){return!1};var i,j,l;function m(a,b,c,d,h,g){var e=document.getElementById(a);if(e){var f=e.style;f.left=d?"auto":b+"px";f.right=d?b+"px":"auto";f.top=c+"px";f.visibility=j?"hidden":"visible";h&&g?(f.width=h+"px",f.height=g+"px"):(m(i,b,c,d,e.offsetWidth,e.offsetHeight),j=j?"":a)}}var n=[],o=function(){j&&m(j,0,0)},q=function(a,b){var c,d=document.getElementById("gbi"),h=a;if(!h)h=d.firstChild;for(;b&&(c=b.pop());){var g=d,e=c,f=h;l||(l="gb2");g.insertBefore(e,f).className=l}};
window.gbar.qs=function(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(a,d){return(d||"&")+"q="+encodeURIComponent(b)})};
window.gbar.tg=function(a){var a=a||window.event,b=a.target||a.srcElement;a.cancelBubble=!0;if(i==null)a=document.createElement(Array.every||window.createPopup?"iframe":"div"),a.frameBorder="0",i=a.id="gbs",a.src="#",document.body.appendChild(a),document.onclick=o;var c=b,b=0;if(c.className!="gb3")c=c.parentNode;var a=c.getAttribute("aria-owns")||"gbi",d=c.offsetWidth,h=c.offsetTop>20?46:24;document.getElementById("tphdr")&&(h-=3);var g=!1;do b+=c.offsetLeft||0;while(c=c.offsetParent);var c=(document.documentElement.clientWidth||
document.body.clientWidth)-b-d,e,d=document.body,f=document.defaultView;f&&f.getComputedStyle?(d=f.getComputedStyle(d,""))&&(e=d.direction):e=d.currentStyle?d.currentStyle.direction:d.style.direction;e=e=="rtl";if(a=="gbi"){for(d=0;f=n[d++];)f();q(null,window.navExtra);e&&(b=c,g=!0)}else e||(b=c,g=!0);j!=a&&o();m(a,b,h,g)};window.gbar.close=o;window.gbar.almm=q;window.gbar.si=function(){return document.getElementById("gb_70")};window.gbar.adh=function(a,b){n.push(b)};var r=-1,s=function(a){var b=/\bgbz0l\b/,a=a.className;return!(!a||!a.match(b))};
window.gbar.slp=function(a){try{var b,c;if(r==-1)a:{var d=document.getElementById("gbar");if(d)for(var h=d.getElementsByTagName("a"),d=0,g;g=h[d++];)if(s(g)){var e,f=/^gb_(\d+)/.exec(g.id);e=f?f[1]:null;if(e!=null){r=e;c=g;break a}break}r=0;c=null}else c=document.getElementById("gb_"+r);b=c;var k=document.getElementById("gb_"+a);if(b){var p=b.className;c=/\s?\bgbz0l\b/;if(p&&p.match(c))b.className=p.replace(c,"")}if(k){var t=k.className;s(k)||(k.className+=(t!=""?" ":"")+"gbz0l")}}catch(u){window.gbar.logger.ml(u)}r=
a};}}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e);}})();
(function(){var f=null;google.rt={};var g=[],h,i,j,k,l,m,n,o,p,q,r,s,t,aa,ba,u,ca,v,w,x;
google.rt.init=function(a,b,c){h=30;i=[];l=k=!1;m="";o=0;p=!1;q=(new Date).getTime();r=100;s=0;t=!1;v=[];w="";j=[];if(n=document.getElementById(a)){if(n.className.indexOf("rtob")>-1)n.style.height=n.clientHeight-google.style.getComputedStyle(n,"padding-top")-google.style.getComputedStyle(n,"padding-bottom")+"px";b&&da(b);if(c)c.maxResults&&(r=c.maxResults),c.promotedTweetRequestUrl&&(w=c.promotedTweetRequestUrl),c.resultUrl&&fa(c.resultUrl);b=function(){p=!0};google.listen(document,"keydown",b);google.listen(document,
"mousemove",b);s+=n.getElementsByTagName("li").length;google.rt.timestampToString=ga;ha();ia();y(z,h);ja(a)&&(A.push(function(){l=!0}),B.push(function(){l=!1}),C(0,!0));ka(3E3);la()}};google.rt.pause=function(){window.clearTimeout(u);ma();var a=document.getElementById("rth").getElementsByTagName("span");D(a[0]);a[1].style.display="";ca=(new Date).getTime()};
google.rt.resume=function(){((new Date).getTime()-ca)/1E3>10&&(i=[]);z();y(z,h);ka(2E3);var a=document.getElementById("rth").getElementsByTagName("span");D(a[1]);a[0].style.display=""};function D(a){a.style.display="none"}function na(a){return Math.min(7200,(Math.random()+0.5)*Math.pow(2,a)*5)}function y(a,b){var c=b;o&&(c=na(o));u=window.setTimeout(function(){a();y(a,b)},c*1E3)}function ka(a){var b=oa;aa=window.setTimeout(function(){b();ba=window.setInterval(b,6E3)},a)}
function ma(){window.clearTimeout(aa);window.clearInterval(ba)}
function oa(){if(!i.length||l){if(t){ma();var a=document.getElementById("rth").getElementsByTagName("span");if(a.length>2)D(a[0]),D(a[1]),a[2].style.display=""}}else{var b=i.shift(),a=b.e,c=a.getElementsByTagName("li")[0];n.insertBefore(a,n.firstChild);b.updateDate();google.History.save(pa,{r:n.innerHTML,u:m,n:s,s:v,t:E()});var b=-google.style.getHeight(c)-google.style.getComputedStyle(c,"margin-bottom"),c=n.scrollTop,d=function(){n.className.indexOf("rtob")==-1&&google.msg.send(48)};c<20?(C(c),google.fx.animate(1200,
[[a,"marginTop",b,0,google.fx.easeInAndOut]],function(){d()})):(C(c-b),d())}}function da(a){if(a.results){for(var b=a.results.length,c=0;c<g.length;++c)g[c](a.results);for(c=b;b=a.results[--c];){var d;a:{d=j;for(var e=d.length;e--;)if(d[e]===b.url){d=!0;break a}d=!1}d||(s++,qa(b.url),i.push(ra(b)))}}a.nextRequest&&(m=a.nextRequest);a.pollSeconds&&(h=a.pollSeconds)}function qa(a){for(j.push(a);j.length>50;)j.shift()}function fa(a){for(var b=0;b<a.length;++b)qa(a[b])}
google.rt.pushRealtimeResultsCallback=function(a){g.push(a)};window.mbrt0=window.a={insert:function(a){a=eval("("+a+")");"numUpdates"in a?sa(a):da(a)}};function z(){if(p)p=!1,q=(new Date).getTime();else if((new Date).getTime()-q>24E4)return;t=s+5>r;if(!k&&!t&&m){var a=google.xhr();a.open("GET",m);a.onreadystatechange=function(){a.readyState==4&&(a.status==200?(eval(a.responseText),o=0):o++,k=!1)};k=!0;a.send(f)}}
window.mbrtpl={insert:function(a){x=!1;var b=eval("("+a+")");if(b.results){var c=b.results.length;if((a=document.getElementById("rtpl"))&&c>0){for(var d;d=b.results[--c];)a.innerHTML+=d.html;a.style.marginTop="-100px";a.style.display="";b=-google.style.getHeight(a)-google.style.getComputedStyle(a,"margin-bottom");a.style.marginTop=b+"px";google.fx.animate(1200,[[a,"marginTop",b,11,google.fx.easeInAndOut]])}}}};
function la(){if(w&&!x){x=!0;var a=google.xhr();a.open("GET",w);a.onreadystatechange=function(){a.readyState==4&&a.status==200&&eval(a.responseText)};a.send(f)}}function ra(a){var b=document.createElement("div");b.innerHTML=a.html;return{e:b,updateDate:ta(b)}}var pa=google.History.client(function(a){n.innerHTML=a.r;m=a.u;s=a.n;v=a.s;F(n,v,a.t);C(0,!0);i=[];z()});google.dstr.push(function(){ma();window.clearTimeout(u)});var G,H,I,J,K,L,M,N,A,B,O,P,Q=!1,R="ontouchstart"in window;function ua(){return Math.max(P/J.scrollHeight*O,20)}function S(a){a=google.browser.product.IE?a.offsetHeight:google.style.getComputedStyle(a,"height");return Number(a)}function va(a){var a=a.offsetTop,b=google.browser.product.IE;if(b&&google.browser.isProductVersion("8")||!b)a-=J.offsetTop;return a}function T(a){if(a)for(var b=0,c;c=A[b++];)c();else if(N)for(b=0;c=B[b++];)c();N=a}
function wa(a){var b=xa(a);if(b){var c=va(b);a||(c+=S(b)-P);M=!0;ya(c,!0,300,function(){M=!1;za(a)})}}function ya(a,b,c,d){var e=J.scrollHeight-P,e=e==0?0:Aa(a*(O-ua())/e,ua()),e=[[I,"marginTop",Number(google.style.getComputedStyle(I,"margin-top")),e,google.fx.easeInAndOut]];b?e.push([J,"scrollTop",J.scrollTop,a,google.fx.easeInAndOut,""]):J.scrollTop=a;google.fx.animate(c,e,d)}function za(a){setTimeout(function(){N&&wa(a)},200)}
function xa(a){var b=J.childNodes;if(a)for(a=b.length-1;a>=0;--a){var c=b[a],d=va(c);if(c.nodeType==1&&d<J.scrollTop)return c}else for(a=0;c=b[a++];)if(d=va(c),c.nodeType==1&&d+S(c)>J.scrollTop+P)return c}function U(a){a.touches&&(a.preventDefault(),a=a.touches[0]);var b=a.clientY-K,b=Aa(Number(google.style.getComputedStyle(I,"margin-top"))+b);I.style.marginTop=b+"px";J.scrollTop=b*(J.scrollHeight-P)/(O-S(I));K=a.clientY}function Aa(a,b){var c=b==f?S(I):b;return Math.max(0,Math.min(O-c,a))}
function C(a,b){if(Q){var c=S(I),d=ua(),c=[[I,"height",c,d],[document.getElementById("sbbb"),"marginTop",c-4,d-4]];if(!L){for(var e=d=0,ea;ea=J.childNodes[e++];)ea.nodeType==1&&(d+=S(ea));if(d>P)document.getElementById("sb").style.display="block",c.push([document.getElementById("sb"),"opacity",0,1,google.fx.linear,""]),L=!0}d=b?0:1200;ya(a,!1,d);google.fx.animate(d,c,function(){if(L)I.style.position="absolute"})}}
function V(a,b){a.parentNode==I&&(a=I);var c=70*(b?1:-1);Ba(a,c);for(var d=0,e;e=a.childNodes[d++];)e.nodeType==1&&Ba(e,c)}function Ba(a,b){var c=a.style.backgroundPosition.match(/^-?\d+/),d=a.style.backgroundPosition.match(/\s+.*$/);a.style.backgroundPosition=parseInt(c,10)+b+"px "+(d?d:"")}
function Ca(){var a=G,b=H,c=I,d=function(){M||(T(!0),wa(!0))};R?google.listen(a,"touchstart",d):google.listen(a,"mousedown",d);a=function(){M||(T(!0),wa())};R?google.listen(b,"touchstart",a):google.listen(b,"mousedown",a);R?google.listen(c,"touchstart",function(a){T(!0);K=a.touches[0].clientY;google.listen(document,"touchmove",U)}):google.listen(c,"mousedown",function(a){T(!0);K=a.clientY;google.listen(document,"mousemove",U)})}
function ja(a){G=document.getElementById("sbu");H=document.getElementById("sbd");I=document.getElementById("sbb");J=document.getElementById(a);if(!G||!H||!I||!J)return Q=!1;N=M=L=!1;A=[];B=[];P=Number(google.style.getComputedStyle(J,"height"));a=P-34;document.getElementById("sbc").style.height=a+"px";O=a-1;document.getElementById("sbbb").marginTop=a-4+"px";document.getElementById("sb").style.display="none";for(var a=[G,H,I],b=0,c;c=a[b++];)google.browser.product.IE?(google.listen(c,"mouseover",function(a){V(a.srcElement)}),
google.listen(c,"mouseout",function(a){V(a.srcElement,!0)}),c.b=function(){return!1}):(google.listen(c,"mouseover",function(a){V(a.target)}),google.listen(c,"mouseout",function(a){V(a.target,!0)}),c.onmousedown=function(){return!1});Ca();return Q=!0}
R?(google.listen(document,"touchend",function(){document.removeEventListener("touchmove",U,!1);T(!1)}),google.dstr.push(function(){A=B=[];Q=!1})):google.listen(document,"mouseup",function(){google.browser.product.IE?document.detachEvent("onmousemove",U):document.removeEventListener("mousemove",U,!1);T(!1)});google.rt||(google.rt={});var Da=-1;google.rt.timestampToString=f;function Ea(a,b){for(var c=a.getElementsByTagName("div"),d=0,e;e=c[d++];)if(e.className=="rtdelta")return b-parseInt(e.innerHTML,10);return!1}function E(){return Math.round((new Date).getTime()/1E3)}
function ga(a,b){var c=b-a;return c<86400?c<45?"秒前":c<105?"1 分钟前":c<3345?"1 分钟前".replace("1",Math.floor(c/60)+(c%60>=45?1:0)+""):c<6600?"1小时前":"1 小时前".replace("1",Math.floor(c/3600)+(c%3600>=3E3?1:0)+""):!1}function Fa(a,b,c){var d=google.rt.timestampToString;if(b&&(b=d(b,c)))a.innerHTML=b}function Ga(a){for(var b=[],a=a.getElementsByTagName("span"),c=0,d;d=a[c++];)d.className.match("rtd")&&b.push(d);return b}
function F(a,b,c){for(var a=Ga(a),c=c||E(),d=0,e;e=a[d];d++)Fa(e,b[d],c)}function ta(a){var b=v,c=E();return function(){var d;d=Ga(a);if(d=d.length>0?d[0]:!1){var e=Ea(d,c);e&&(Fa(d,e,E()),b.unshift(e))}}}function ha(a){for(var b=v,c=Ga(n),a=a||E(),d=0,e;e=c[d++];)(e=Ea(e,a))&&b.push(e)}function ia(){var a=n,b=v;Da=window.setInterval(function(){F(a,b)},6E4);google.dstr.push(function(){window.clearInterval(Da)})};google.rt.replayCallbacks=[];google.rt.pushReplayCallback=function(a){google.rt.replayCallbacks.push(a)};function Ha(){google.rt.timestampToString=function(a){return google.rt.formatTime(a,"FullDate")}}var Ia=google.History.client(function(a){n.innerHTML=a.r;v=a.s;F(n,v,a.t)});google.rt.replayinit=function(a){n=document.getElementById(a);v=[];Ha();n&&(google.rt.pushReplayCallback(function(){ha(f);F(n,v)}),window.setTimeout(function(){google.History.save(Ia,{r:n.innerHTML,s:v,t:E()})},100))};google.rtc={};var Ja,Ka,W,X,La,Ma,Y,Na,Oa,Z,$,Pa;google.rtc.init=function(a,b){var c;if(c=b)(Ja=document.getElementById(a))?(Ka=parseInt(Ja.innerHTML,10),W=0,Ma="",Y=!1,Na=(new Date).getTime(),Z=Oa=0,$=!1,La=X=0,c=!0):c=!1;c&&(sa(b),c=function(){Y=!0},google.listen(document,"keydown",c),google.listen(document,"mousemove",c),Qa(Ra,1))};
function Qa(a,b){Y&&(Y=!1,Na=(new Date).getTime());if(!(Oa>200||Z>3||(new Date).getTime()>Na+24E4)){Sa();var c=b;Z&&(c=na(Z));var d;$||W!=0?d=function(){Qa(a,b)}:(X=0,d=function(){a();Qa(a,b)});Pa=window.setTimeout(d,c*1E3)}}function Ra(){var a=google.xhr();a.open("GET",Ma);a.onreadystatechange=function(){a.readyState==4&&(a.status==200?(eval(a.responseText),Z=0):Z++);$=!1};$=!0;a.send(f)}function sa(a){a.numUpdates&&(X=a.numUpdates);a.nextRequest&&(Ma=a.nextRequest)}
function Sa(){if(!$){Oa++;W++;W>=30&&(W-=30);var a=La+X/30,b=Math.round(a);La=a-b;Ka+=b;Ja.innerHTML=Ka}}google.dstr.push(function(){window.clearTimeout(Pa)});})();
(function(){function f(){function b(a){return{api:a,G:a.a,J:a.b,F:a.c,da:a.d,ea:a.e,aa:a.f,ba:a.g,$:a.h,Z:a.i,Y:a.j,ca:a.k,I:a.l,K:a.m,L:a.n,M:a.o,O:a.p,P:a.q,Q:a.r,N:a.s,W:a.t,B:a.u,ga:a.v}}var c=window.google.comm;return!c?null:{D:function(a,d){var e=c.h(a,d);return b(e)},fa:function(a){return b(a.api)},H:c.a,R:c.b,S:c.c,T:c.d,V:c.e,U:c.f,C:c.g,X:c.i,z:c.j}};var g=!1,h=function(){};function j(b,c,a){var d=document.getElementById("set_location_section");if(b.innerHTML!="")d.style.height=d.offsetHeight-b.offsetHeight-4+"px";var e=d.offsetHeight,i="";a&&(i="color:#c11;");b.innerHTML='<div style="'+i+'margin-top:3px">'+c+"</div>";b.style.display="block";if(d.offsetHeight==e)d.style.height=d.offsetHeight+b.offsetHeight+4+"px"}function k(){var b={q:google.nav.getQuery(),changed_loc:1};google.nav.search(b,!0)}
function l(b){var c=document.getElementById("error_section"),a=google.xhr();a.onreadystatechange=function(){if(a.readyState==4)if(a.status==200&&!a.responseText){c.innerHTML="";try{var b=f();b&&b.z()}catch(e){google.log("location_widget_make_uul_request","&err="+e+"&ei="+google.kEI)}k()}else a.status==200&&a.responseText?a.responseText.match("\n")?j(c,a.responseText.split("\n")[0],!0):j(c,a.responseText,!1):j(c,google.loc.m3,!0)};a.open("GET","/uul?muul=4_18"+b+"&usg="+encodeURIComponent(google.loc.s)+
"&hl="+google.kHL,!0);a.send(null)}var m=function(){google.log("location_widget_enable_autodetect","&ei="+google.kEI);l("&uulo=2")};function n(b){if(!b)return null;var c=b.offsetHeight,a=google.style.getComputedStyle(b,"overflow",!0);b.style.overflow="hidden";return{w:c,A:a}}google.loc=google.loc||{};google.loc.init=h;google.loc.enableAutoDetect=m;
google.loc.submit=function(){var b=document.getElementById("lc-input").value;b?(google.log("location_widget_change_location","&ei="+google.kEI),l("&luul="+encodeURIComponent(b)+"&uulo=1")):m();return!1};google.loc.f=function(){var b=document.getElementById("lc-input");if(b.value==google.loc.m4)b.value="",b.style.color="#000000"};google.loc.b=function(){var b=document.getElementById("lc-input");if(b.value=="")b.value=google.loc.m4,b.style.color="#666666"};
google.loc.toggleLocationChange=function(){if(!g){g=!0;var b=document.getElementById("lc"),c=document.getElementById("set_location_section"),a=google.style.hasClass(b,"lco");b.className="lco";var d=n(c);google.fx.animate(227,[[c,"height",a?d.w:0,a?0:d.w],[c,"opacity",a?1:0,a?0:1,null,""]],function(){if(a)b.className="";google.log("location_widget","&open="+(a?"0":"1")+"&ei="+google.kEI);a?c.style.height=d.w+"px":c.style.removeAttribute&&c.style.removeAttribute("filter");c.style.overflow=d.A;g=!1})}};
google.loc.devloc=function(){var b=document.getElementById("error_section");google.devloc?google.devloc.pnlic(k,function(){j(b,google.loc.m5,!0)}):j(b,google.loc.m5,!0)};google.register(77,{init:h});})();
(function(){google.tbpr={};var d={},f=/\bl\b/,h=function(c){return f.test(c.className)},i=function(c){var b="",a;for(a in d)d[a].style.display="none";if(c&&c.a>=0){b=c.a;if(d[b])d[b].style.display="block";b="tbpr:idx="+c.a}return b},j=function(c,b){b==null&&(b={});b.a=c.b||-1;google.event.back.saveHistory("tbpr",b)};
google.register(78,{init:function(){d={};for(var c=document.getElementsByTagName("h3"),b=0,a;a=c[b++];)if(a.className=="tbpr"){var g=Number(a.id.substr(5));for(d[g]=a;a&&a.nodeName!="LI";)a=a.parentNode;if(a){a=a.getElementsByTagName("a");for(var k=0,e=void 0;e=a[k++];)if(h(e)){e.b=g;break}}}google.event.back.register(h,j,i,"tbpr")}});})();
(function(){var e=null;google.LU={};
google.register(84,{init:function(a){google.LU.u=a.no_tt;document.getElementById("rhs_map")&&(google.browser.engine.IE&&google.browser.compareVersions("7",google.browser.product.version)==0||google.browser.product.IPAD||document.getElementById("tbt5")||j());k=!1;if(google.LU.fmap_url_delta&&(l=document.getElementById("lu_map"))){for(m=l;m&&m.tagName!="A";)m=m.parentNode;n=document.getElementById("rhs_map");o=(a=document.getElementById("center_col"))&&a.parentNode||document.getElementById("ires");if(m&&
o&&(p=m.href,q=p.search(/&iwloc=|&cid=0,0,/)!=-1,a=l,a.tagName=="IMG"?a=a.src:(a=/url\(([\'\"]?)(.*)\1\)/.exec(a.style.background),a=!a||a.length<3?"":a[2]),a)){var b=a.indexOf("data=")+5,c=a.indexOf(",")+1;r=a.substring(0,c);s=a.substring(0,b)+google.LU.fmap_url_delta+",";t=0;u={id:t++,token:a.substring(c),featuresCallback:e};google.LU.u||(v=new google.LU.g(!google.style.isRtl()));w={x:0,y:0};x=google.util.rateLimitFunction(e,aa,100,!0);u.featuresCallback=ba;y=[u];z=new google.LU.w(r,s,"0",[u.token],
o,!0);k=!!z;A["0"]=z;z.key="0";google.listen(l,"mousemove",C);google.listen(window,"scroll",E);google.listen(window,"pagehide",F);google.listen(l,"mouseout",G)}}},dispose:function(){l&&(google.unlisten(l,"mousemove",C),google.unlisten(window,"scroll",E),google.unlisten(window,"pagehide",F),google.unlisten(l,"mouseout",G));n=o=m=l=e;p="";q=!1;z=e;y.length=0;H.length=0;A={};u=e;t=0;k=!1;if(v){var a=v;a.d&&a.d.parentElement&&a.d.parentElement.removeChild(a.d);v=e}x=w=e;I&&(google.unlisten(window,"scroll",
J),google.browser.engine.IE||google.unlisten(window,"resize",K),L&&window.clearInterval(L),I=e);delete google.LU.u}});var l,m,o,n,p,q,r,s,M,z,y=[],H=[],A={},u,t=0,v,w,k=!1,x=e;
function aa(){if(z&&z.k()){M=l.offsetHeight;var a;if(google.browser.engine.IE){a=l.getBoundingClientRect();var b=l.ownerDocument;a.left-=b.documentElement.clientLeft+b.body.clientLeft;a.top-=b.documentElement.clientTop+b.body.clientTop;a={x:w.x-a.left,y:w.y-a.top}}else b=(a=n&&n.style.position=="fixed")?0:document.body.scrollTop+document.documentElement.scrollTop,a={x:w.x+(a?0:document.body.scrollLeft+document.documentElement.scrollLeft)-google.style.getPageOffsetLeft(l),y:w.y+b-google.style.getPageOffsetTop(l)};
b=z.h;b=(b.j[3]-b.j[1])/M;b={x:a.x*b,y:a.y*b};a=b.x;for(var b=b.y,c=z.h,d=[],f=0,i;i=c.v[f];++f)i.contains(a,b)&&d.push(i);m.href=N(d)}}function C(a){a=a||window.event;w.x=a.clientX;w.y=a.clientY;x()}function E(){x()}function G(){w.x=w.y=0;m.href=N([])}function F(){w.x=w.y=0;O(v)}function N(a){var f;for(var b=p,c=0,d;d=y[c++];)(f=(d=d.featuresCallback)&&d(a),d=f)&&(b=d);return b}
function ba(a){m.style.cursor=a.length==0?"default":"pointer";for(var b=e,c=0,d;d=a[c++];){if(d.id=="0")return e;d.z&&(b=d)}a=b&&[b]||a;if(!google.LU.u)b=a,c={x:6*(google.style.isRtl()?1:-1),y:12},ca(b,{x:w.x+c.x,y:w.y+c.y}),v.b.length&&(a=v.b);if(a.length==0||q)a=p;else{b=[];for(c=0;d=a[c++];)b.push(d.id);a=b.length?p+"&iwloc=cids:"+b.join(","):e}return a}google.LU.addMapConfig=function(a){if(!k)return!1;a.id||(a.id=t++);y.push(a);P();return!0};
google.LU.replaceMapConfig=function(a){if(!k||!a.token)return!1;a.id||(a.id=t++);H.push(y);y=[a];P();return!0};google.LU.deleteMapConfig=function(a){if(a.id!="0"){for(var b=0;b<y.length;++b)y[b].id==a.id&&y.splice(b,1);y.length==0&&(y=H.pop());P()}};function P(){for(var a=[],b=0,c;c=y[b++];)c.token&&a.push(c);for(var d=[],f=[],b=0;c=a[b++];)d.push(c.id),f.push(c.token);a=d.join("_");b=A[a];b||(b=new google.LU.w(r,s,a,f,o,!1),A[a]=b);b!=z&&(da(b),z=b)};google.LU.w=function(a,b,c,d,f,i){this.A=0;this.h=e;d=d.join(",");this.I=a+d;var g="loadFeaturemap"+c,h=this;google.LU[g]=function(a){delete google.LU[g];h.i&&(h.i.parentNode.removeChild(h.i),delete h.i);h.h=new google.LU.H(a);google.log("lu_featuremap",google.time()-h.A+"")};a=[b,d,"&callback=google.LU.",g].join("");i?ea(this,a,f):this.i=Q(this,a)};
var da=function(a){var b=l,c=a.I,d=b.cloneNode(!0);google.dom.set(d,"position","absolute");d.onload=function(){google.dom.insert(d,b);google.fx.animate(100,[[d,"opacity",0,1,e,""]],function(){b.src=c;google.dom.remove(d)})};d.src=c},Q=function(a,b){a.A=google.time();var c=document.createElement("SCRIPT");c.src=b;google.dom.append(c);return c},ea=function(a,b,c){c.B=!0;c.n=function(){if(c.B)c.B=!1,google.unlisten(c,"mouseover",c.n),google.unlisten(c,"mousemove",c.n),a.i=Q(a,b)};google.listen(c,"mouseover",
c.n);google.listen(c,"mousemove",c.n)};google.LU.w.prototype.k=function(){return!!this.h&&this.h.k};google.LU.Feature=function(a){this.m=a.a;this.e=a.bb;this.id=a.id;var b={};if("c"in a)try{b=eval("(0,"+a.c+")")}catch(c){}if(b&&b["9"]&&google.LU.fmap_xc){var a=google.LU.fmap_xc[b["9"].index],d;for(d in a)b[d]=a[d]}this.extendedContent=b;this.z=!(!b||!(b["9"]&&b["9"].index.substr(0,1)=="r"))};google.LU.Feature.prototype.z=!1;google.LU.Feature.prototype.height=function(){return this.e[3]-this.e[1]+1};google.LU.Feature.prototype.width=function(){return this.e[2]-this.e[0]+1};
google.LU.Feature.prototype.top=function(){return this.m[1]-this.height()+1};google.LU.Feature.prototype.left=function(){return this.m[0]+this.e[0]+1};google.LU.Feature.prototype.contains=function(a,b){var c=a-this.m[0],d=b-this.m[1];return c>=this.e[0]&&d>=this.e[1]&&c<=this.e[2]&&d<=this.e[3]};google.LU.H=function(a){this.j=e;this.v=[];this.k=!1;var b;if(a){b=0;for(var c;b<a.length;++b)if(c=a[b].features)for(var d=0,f;f=c[d];++d)this.v.push(new google.LU.Feature(f));b=this.v.length>0}else b=!1;if(b&&(this.j=a[0].rectangle)&&this.j.length==4)this.k=!0};google.LU.g=function(a){this.s=0;this.b=[];this.d=document.createElement("div");var b=this.d.style;b.position="fixed";b.WebkitTransitionProperty="left, top";b.O=".1s, .1s";b.P="left, top";b.WebkitTransitionDuration=".1s, .1s";this.p=document.createElement("div");b=this.p.style;b.position="absolute";b.zIndex=110;b.border="1px solid #999";b.padding="3px 6px";b.lineHeight="1.2";b.fontSize="85%";b.backgroundColor="#ffffd5";b.whiteSpace="nowrap";b.WebkitBoxShadow="2px 2px 5px rgba(0, 0, 0, 0.5)";b.N="2px 2px 5px rgba(0, 0, 0, 0.5)";
a?b.right=0:b.left=0;this.d.appendChild(this.p);O(this);google.dom.append(this.d)};google.LU.g.F=5;google.LU.g.G=200;
var ca=function(a,b){var c=v;fa(c,a)&&(c.s++,setTimeout(function(){c.s--;if(c.s==0)if(c.b.length){for(var a=[],f=0,i;f<google.LU.g.F&&(i=c.b[f++]);){var g=R(i);if(g.title){c.b.length!=1&&a.push('<div style="min-height: 16px">');a.push("<b>",g.title,"</b> ");var h=g.star_rating,g=g.review_count,B=a;if(!(typeof h=="undefined"||typeof g=="undefined")){B.push('<div style="display: inline-block; vertical-align: -2px">');for(var Z=0;Z<5;++Z){var D;h>0.75?(D="rsw-starred",h-=1):h>0.25?(D="rsw-half-starred",
h-=0.5):D="rsw-unstarred";B.push('<div style="float: none; display: inline-block" class="',D,'"></div>')}B.push("</div>");B.push("<span dir=",google.style.isRtl()?"dir=rtl":"","> (",g,") </span>")}c.b.length!=1&&a.push("</div>")}}c.b.length==1&&(f=(g=R(c.b[0]))&&g.snippet,i=g&&g.snippet_attribution,f&&i&&(a.push('<div style="min-width: 150px; white-space: normal">',f,"</div>"),a.push('<div style="color: #666">',i,"</div>")));c.p.innerHTML=a.join("");c.d.style.left=b.x+"px";c.d.style.top=b.y+"px";
c.d.style.display=""}else O(c)},google.LU.g.G))};function R(a){return a.extendedContent&&a.extendedContent["1"]}function S(a,b){for(var c=0,d;d=b[c++];)if(d.id==a)return!0;return!1}
var fa=function(a,b){for(var c=!1,d=0,f;f=a.b[d];)S(f.id,b)?d++:(a.b.splice(d,1),c=!0);for(var d=0,i;i=b[d++];)if(!S(i.id,a.b)){f=a;var g=R(i);if(g){if(typeof g.star_rating=="undefined")f.b.push(i);else{for(var h=void 0,h=0;h<f.b.length;++h)if((g=R(f.b[h]))&&typeof g.star_rating=="undefined")break;f.b.splice(h,0,i)}f=!0}else f=!1;f&&(c=!0)}return c},O=function(a){a.d.style.display="none"};var T,U,V=!0,I,L,ga=["left","margin","paddingTop","position","top","width","zIndex"],W={},X={};function Y(a){return google.browser.engine.IE?document.documentElement["client"+a]:window["inner"+a]}function ha(){if(I)for(var a in W)I.style[a]=W[a]}function ia(){var a=document.getElementById("rhs_map-placeholder");a&&a.parentNode.removeChild(a)}
function J(){if(V&&!((document.body.scrollLeft||document.documentElement.scrollLeft)>0)){var a=document.body.scrollTop+document.documentElement.scrollTop;if(!U&&a>=T){if(I){X.Q=google.style.getPageOffsetLeft(I);X.K=google.style.getWidth(I);X.M=I.offsetWidth;X.L=I.offsetHeight;for(var a=0,b;b=ga[a++];)W[b]=I.style[b]}if(I){if(google.style.getComputedStyle(I,"position",!0)!="absolute")a=document.createElement("div"),a.id=I.id+"-placeholder",google.browser.engine.IE?a.style.styleFloat=google.style.getComputedStyle(I,
"styleFloat",!0):a.style.cssFloat=google.style.getComputedStyle(I,"float",!0),a.style.width=X.M+"px",a.style.height=X.L+"px",a.style.marginTop=google.style.getComputedStyle(I,"margin-top",!0),a.style.marginBottom=google.style.getComputedStyle(I,"margin-bottom",!0),a.style.marginLeft=google.style.getComputedStyle(I,"margin-left",!0),a.style.marginRight=google.style.getComputedStyle(I,"margin-right",!0),I.parentNode.insertBefore(a,I.nextSibling);I.style.margin=0;I.style.zIndex=109;I.style.width=X.K+
"px";I.style.top=0;I.style.position="fixed";I.style.paddingTop="5px"}U=!0}else U&&a<T&&(ia(),ha(),U=!1)}}function ja(){if(!I)return!1;var a=document.getElementById("rhs_block");if(!a)return!1;var b=a.getElementsByTagName("li");if(!b||b.length==0)return!1;var a=Y("Height"),c=google.style.getHeight(I),b=2*(b[0].offsetHeight+12)+c+google.style.getPageOffsetTop(I);return a<b}function K(){U&&(ia(),ha(),U=!1);ja()?V=!1:(V=!0,T=google.style.getPageOffsetTop(document.getElementById("leftnav")),J())}var $;
function ka(){if(I)this.C=google.style.getHeight(I),this.o=Y("Height"),this.D=Y("Width"),this.J=function(){var a=$;return google.browser.engine.IE?this.C==a.C&&this.o==a.o&&this.D==a.D:this.o==a.o}}function la(){if(I){var a=new ka;a.J()||(K(),$=a)}}
function j(){google.listen&&google.style.getHeight?(I=document.getElementById("rhs_map"),W={},X={},$=new ka,google.listen(window,"scroll",J),google.browser.engine.IE?L=window.setInterval(la,200):google.listen(window,"resize",K),K()):window.setTimeout(function(){j()},100)};})();
(function(){google.onebox={};var j=!0,t=function(b,d,c,e,k,l){for(var a=[],m=[],n=b?1:0,p=1-n,f,g,h,q=google.dom.getAll("div.obsmw",d),d=google.style,s=0,i;i=q[s++];)f=i.offsetHeight,google.browser.WEBKIT?(h=d.getWidth(i.parentNode),g=-100*f/h-10,h="%"):(g=-f-1,h="px"),f=(1-n)*g,g*=1-p,a.push([i,"marginTop",f,g,google.fx.linear,h]),m.push([i.parentNode,"opacity",n,p,google.fx.linear,""]);var o=google.fx.animate,r=function(){var a=q,c=!b;j=!0;if(c){typeof a.length=="undefined"&&(a=[a]);for(var c=0,d;d=a[c++];)google.browser.engine.IE?
d.parentNode.style.removeAttribute("filter"):d.parentNode.style.opacity=""}l&&l()};c?o(e,m.concat(a),r):(c=function(a,b,c,d){o(c,a,function(){o(d,b,r)})},b?c(m,a,e,k):c(a,m,k,e))};
google.onebox.sm={toggle:function(b,d,c,e,k,l){if(j){for(j=!1;!google.style.hasClass(b,"obcontainer");){if(b==document.body){j=!0;return}b=b.parentNode}var a=google.style.hasClass(b,"obsmo");a?google.style.removeClass(b,"obsmo"):google.style.addClass(b,"obsmo");t(a,b,d,c,k,l);google.log("prose_onebox_show_more",(a?"close":"open")+"&id="+e)}}};})();
(function(){if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return!1};google.y.first=[];})();
(function(){if(window.google){window.google.a={};window.google.c=1;var j=function(a,b,e){b=a.t[b];a=a.t.start;if(b&&(a||e))return e!=void 0&&(a=e),b>a?b-a:a-b},k=function(a,b,e){var c="";window.google.pt&&(c+="&srt="+window.google.pt,delete window.google.pt);var d=document.getElementById("csi");if(d){var f;window.google._bfr!=void 0?f=window.google._bfr:(f=d.value,window.google._bfr=f,d.value=1);if(f)return""}if(d=window.chrome)if(d=d.loadTimes)d().wasFetchedViaSpdy&&(c+="&p=s"),d().wasNpnNegotiated&&(c+="&npn=1"),
d().wasAlternateProtocolAvailable&&(c+="&apa=1");a.b&&(c+="&"+a.b);window.parent!=window&&(c+="&wif=1");d=a.t;f=d.start;var h=[],g;for(g in d)g!="start"&&f&&h.push(g+"."+j(a,g));delete d.start;if(b)for(var i in b)c+="&"+i+"="+b[i];return a=[e?e:"/csi","?v=3","&s="+(window.google.sn||"GWS")+"&action=",a.name,"",c,"&rt=",h.join(",")].join("")};window.google.report=function(a,b,e){a=k(a,b,e);if(!a)return"";var b=new Image,c=window.google.c++;window.google.a[c]=b;b.onload=b.onerror=function(){delete window.google.a[c]};
b.src=a;b=null;return a}};function l(){function a(a){try{var b=window.external[a];if(b!=void 0)return google.kCSI[a]=b,!0}catch(c){}return!1}for(var b=["ist_rc","ist_rn","ist_nr","ist_cdts","ist_dp","ist_rrx","ist_rxr","ist_rs","ist_sr"],e=0,c;c=b[e++];)if(a(c)===!1)break}
if(google.timers&&google.timers.load.t){if(!google.nocsixjs)google.timers.load.t.xjsee=google.time();window.setTimeout(function(){if(google.timers.load.t)google.timers.load.t.xjs=google.time(),l(),google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)},0)};})();
